[package]
name = "nazonazo_macros"
version = "0.1.0"
authors = ["Mitama <loligothick@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["nightly"] }
quote = "1.0"
syn = { version = "1.0.5", features = ["full"] }
